# file: book.toml
[book]
authors = ["mcs-pt-team"]
language = "en"
src = "src"
title = "survive-mcs-manual"
[build]
build-dir = "../../docs/survive-mcs-manual"
[output.html.fold]
enable = true   # 开启折叠功能
level = 0       # 折叠从第几层开始（可根据需要调整）
